### ISSUE TITLE
Info for Greg: Logging in to plugin.govready.com

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Agent-Client#1]
@gregelin Here's the login info for the demo of the dashboard on  plugin.govready.com:
- url: https://plugin.govready.com
- username: test@proudcity.com
- password: test

Login screen:
@todo: we should style+brand this if we want to use this.
![screenshot from 2016-10-30 12 16 45](https://cloud.githubusercontent.com/assets/550909/19839197/d30772c8-9e9a-11e6-892a-75d9586ae224.png)

Once logged in:
![screenshot from 2016-10-30 12 15 58](https://cloud.githubusercontent.com/assets/550909/19839200/d7e35ec4-9e9a-11e6-8c65-4a2f972ab87a.png)

**Comment by gregelin** [comment]
That is spectacular!  Customers might even like this standalone better than plugin. It can be set up for any site right?

Greg

**Comment by jlyon** [comment]
Yes, you can select the site you want to view the dashboard for after you login.

**Comment by gregelin** [comment]
@jlyon @aschmoe Have you pushed the latest version to https://plugin.govready.com? I'm still not able to add a new site.

**Comment by jlyon** [comment]
@gregelin  Sorry, we didn't pull the client code on plugin.govready.com last night.  We just pulled it, and the site creation screen is now working (you need to select Other under application -- Drupal/WP instruct you to download the plugin/module.
