### ISSUE TITLE
Logout doesn't appear if user has no sites

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Agent-Client#6]

**Comment by jlyon** [comment]
@aschmoe I think this is fixed,  right?

**Comment by aschmoe** [comment]
@jlyon it is now

**Comment by jlyon** [comment]
@aschmoe within Q, the log out link takes you to plugin.govready.com. Could you change the return-to param in the auth0 logout url to the current url (`window.location`?) instead of hardcoding it?
